name: PySpark CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyspark pandas

      # Step 4: Verify input file exists
      - name: Check input file
        run: |
          if [ ! -f "student_data_with_duplicates.csv" ]; then
            echo "❌ Input file not found! Please upload student_data_with_duplicates.csv"
            exit 1
          fi

      # Step 5: Run PySpark Script
      - name: Run PySpark Job
        run: python your_script.py

      # Step 6: Upload cleaned CSV as artifact
      - name: Upload Cleaned Data
        uses: actions/upload-artifact@v4
        with:
          name: cleaned-data
          path: cleaned_student_data_with_duplicates.csv/
